import { PrismaClient, TrainingCategory } from '@prisma/client';

const prisma = new PrismaClient();

const sampleQuestions = [
  {
    id: 1,
    category: TrainingCategory.PPR_ANALISIS,
    topic: 'Regulasi BAPETEN',
    difficulty: 1,
    questionText: 'Berdasarkan Peraturan BAPETEN No. 4 Tahun 2024, Nilai Batas Dosis (NBD) efektif untuk pekerja radiasi adalah...',
    optionA: '10 mSv per tahun',
    optionB: '20 mSv per tahun rata-rata dalam 5 tahun berturut-turut',
    optionC: '50 mSv per tahun',
    optionD: '100 mSv dalam 5 tahun',
    optionE: '5 mSv per tahun',
    correctAnswer: 'B',
    explanation: 'Berdasarkan Perba BAPETEN No. 4 Tahun 2024, NBD dosis efektif untuk pekerja radiasi adalah 20 mSv per tahun rata-rata selama 5 tahun berturut-turut, dengan batas maksimal 50 mSv dalam satu tahun tunggal.',
    isActive: true,
  },
  {
    id: 2,
    category: TrainingCategory.PPR_ANALISIS,
    topic: 'Fisika Radiasi',
    difficulty: 2,
    questionText: 'Suatu sumber radiasi Co-60 memiliki aktivitas awal 100 Ci. Jika waktu paruh Co-60 adalah 5,27 tahun, berapakah sisa aktivitas sumber tersebut setelah 10,54 tahun?',
    optionA: '50 Ci',
    optionB: '25 Ci',
    optionC: '12,5 Ci',
    optionD: '6,25 Ci',
    optionE: '10 Ci',
    correctAnswer: 'B',
    explanation: 'Menggunakan rumus peluruhan radioaktif: A(t) = A0 × (1/2)^(t / T½) = 100 × (1/2)^(10,54 / 5,27) = 100 × (1/2)^2 = 100 × 0,25 = 25 Ci.',
    isActive: true,
  },
  {
    id: 3,
    category: TrainingCategory.PPR_ANALISIS,
    topic: 'Efek Biologi Radiasi',
    difficulty: 1,
    questionText: 'Efek stokastik dari radiasi pengion ditandai dengan...',
    optionA: 'Ada nilai ambang dosis yang jelas',
    optionB: 'Keparahan efek bergantung pada dosis yang diterima',
    optionC: 'Probabilitas terjadinya efek bergantung pada dosis tanpa nilai ambang',
    optionD: 'Efek langsung terlihat dalam waktu singkat setelah penyinaran',
    optionE: 'Hanya terjadi pada dosis sangat tinggi di atas 1 Gy',
    correctAnswer: 'C',
    explanation: 'Efek stokastik (seperti karsinogenesis dan mutasi genetik) tidak memiliki nilai ambang dosis. Probabilitas terjadinya efek meningkat seiring dosis, namun tingkat keparahannya tidak dipengaruhi besarnya dosis.',
    isActive: true,
  },
  {
    id: 4,
    category: TrainingCategory.PPR_ANALISIS,
    topic: 'Alat Ukur Radiasi',
    difficulty: 2,
    questionText: 'Detektor yang paling sesuai untuk mengukur laju dosis radiasi gamma di lapangan dengan respon real-time dan ketergantungan energi rendah adalah...',
    optionA: 'Dosimeter TLD (Thermo Luminescent Dosimeter)',
    optionB: 'Film badge personal',
    optionC: 'Ionization chamber (kamar ionisasi)',
    optionD: 'Bubble detector neutron',
    optionE: 'Etched track detector',
    correctAnswer: 'C',
    explanation: 'Kamar ionisasi (ionization chamber) memberikan respon laju dosis gamma/sinar-X yang linier dan presisi secara seketika (real-time) dengan ketergantungan energi yang relatif datar.',
    isActive: true,
  },
  {
    id: 5,
    category: TrainingCategory.PPR_ANALISIS,
    topic: 'Proteksi Radiasi',
    difficulty: 1,
    questionText: 'Prinsip optimisasi proteksi radiasi dikenal dengan konsep ALARA, yang merupakan akronim dari...',
    optionA: 'Always Low And Radiation Achievable',
    optionB: 'As Low As Reasonably Achievable',
    optionC: 'Applied Limit And Radiation Acceptable',
    optionD: 'Authorized Level And Radiation Allowance',
    optionE: 'Achieved Limit As Radiation Allows',
    correctAnswer: 'B',
    explanation: 'ALARA (As Low As Reasonably Achievable) adalah prinsip optimisasi proteksi radiasi dengan mempertimbangkan faktor ekonomi dan sosial guna menekan dosis serendah mungkin.',
    isActive: true,
  },
  {
    id: 6,
    category: TrainingCategory.PPR_ANALISIS,
    topic: 'Keadaan Darurat Radiasi',
    difficulty: 2,
    questionText: 'Langkah pertama yang harus diambil ketika terjadi insiden tumpahan atau kebocoran zat radioaktif cair di laboratorium adalah...',
    optionA: 'Membersihkan tumpahan segera dengan kain lap tanpa melapor',
    optionB: 'Mengumpulkan bahan radioaktif ke satu wadah plastik biasa',
    optionC: 'Mengevakuasi personel, memasang tanda isolasi, dan segera melapor kepada PPR',
    optionD: 'Membuka seluruh jendela dan pintu ruangan selebar-lebarnya',
    optionE: 'Menunggu cairan mengering sebelum mengambil tindakan',
    correctAnswer: 'C',
    explanation: 'SOP darurat kontaminasi: 1) Evakuasi personil dari area terkontaminasi, 2) Isolasi ruangan agar tidak menyebar, 3) Laporkan seketika kepada Petugas Proteksi Radiasi (PPR) untuk tindakan terkoordinasi.',
    isActive: true,
  },
  {
    id: 7,
    category: TrainingCategory.PPR_BAGASI,
    topic: 'Regulasi BAPETEN',
    difficulty: 1,
    questionText: 'Petugas operator mesin sinar-X pemindai bagasi (cabin / cargo X-ray) dalam ketenaganukliran diklasifikasikan sebagai...',
    optionA: 'Masyarakat umum non-radiasi',
    optionB: 'Pekerja radiasi yang wajib memperoleh pelatihan proteksi dan pemantauan dosis',
    optionC: 'Pekerja magang tanpa pengawasan',
    optionD: 'Inspektur keselamatan BAPETEN',
    optionE: 'Tenaga medis radiologi',
    correctAnswer: 'B',
    explanation: 'Operator pesawat sinar-X bagasi bekerja di lingkungan sumber radiasi pengion, sehingga berstatus Pekerja Radiasi yang berhak dan wajib mendapatkan pelatihan proteksi radiasi serta pemantauan dosis perorangan.',
    isActive: true,
  },
  {
    id: 8,
    category: TrainingCategory.PPR_BAGASI,
    topic: 'Keselamatan Sinar-X Bagasi',
    difficulty: 2,
    questionText: 'Sesuai standar keselamatan BAPETEN, batas laju kebocoran radiasi pada jarak 5 cm dari permukaan eksternal mesin sinar-X bagasi tidak boleh melebihi...',
    optionA: '5 µSv/jam (0,5 mR/jam)',
    optionB: '50 µSv/jam (5 mR/jam)',
    optionC: '100 µSv/jam (10 mR/jam)',
    optionD: '1 mSv/jam',
    optionE: '10 mSv/jam',
    correctAnswer: 'A',
    explanation: 'Berdasarkan standar proteksi radiasi untuk pesawat sinar-X bagasi tertutup (cabinet X-ray system), laju dosis kebocoran di luar kabinet pada jarak 5 cm dari permukaan tidak boleh melampaui 5 µSv/jam (0,5 mR/jam).',
    isActive: true,
  },
  {
    id: 9,
    category: TrainingCategory.PPR_BAGASI,
    topic: 'Komponen & Perisai',
    difficulty: 1,
    questionText: 'Tirai bertimbal (lead curtains) yang dipasang pada pintu masuk dan keluar terowongan inspeksi bagasi berfungsi untuk...',
    optionA: 'Mencegah bagasi tergelincir dari ban berjalan (conveyor belt)',
    optionB: 'Menahan radiasi hambur (scattered radiation) agar tidak keluar dari terowongan',
    optionC: 'Membersihkan debu pada permukaan koper penumpang',
    optionD: 'Mendeteksi bahan peledak secara otomatis',
    optionE: 'Mengurangi kebisingan suara motor mesin',
    correctAnswer: 'B',
    explanation: 'Tirai bertimbal (lead curtains) mengandung ekuivalen Pb tertentu yang berfungsi menahan radiasi hambur sinar-X yang timbul saat berkas utama menumbuk bagasi di dalam terowongan.',
    isActive: true,
  },
  {
    id: 10,
    category: TrainingCategory.PPR_BAGASI,
    topic: 'Prosedur Operasional',
    difficulty: 2,
    questionText: 'Apabila barang bawaan/koper tersangkut (jammed) di tengah terowongan inspeksi sinar-X, tindakan yang BENAR adalah...',
    optionA: 'Memasukkan tangan ke dalam terowongan melewati tirai timbal saat generator menyala',
    optionB: 'Mematikan pembangkit sinar-X (X-ray OFF / Power OFF) terlebih dahulu sebelum mengambil barang',
    optionC: 'Mendorong koper tersebut menggunakan koper penumpang berikutnya',
    optionD: 'Meningkatkan tegangan tabung (kV) agar barang terbakar',
    optionE: 'Membiarkan koper di dalam hingga mesin mati dengan sendirinya',
    correctAnswer: 'B',
    explanation: 'Dilarang keras memasukkan anggota tubuh ke dalam terowongan saat sinar-X aktif. Tombol X-ray OFF atau emergency stop harus ditekan terlebih dahulu sebelum melakukan penanganan barang yang tersangkut.',
    isActive: true,
  },
  {
    id: 11,
    category: TrainingCategory.PPR_BAGASI,
    topic: 'Sistem Keselamatan',
    difficulty: 2,
    questionText: 'Interlock pengaman (safety interlock switch) pada panel penutup mesin sinar-X bagasi berfungsi untuk...',
    optionA: 'Menghentikan pancaran sinar-X seketika apabila panel penutup dibuka',
    optionB: 'Mengunci kecepatan conveyor belt',
    optionC: 'Mengatur ketajaman kontras monitor inspeksi',
    optionD: 'Menghubungkan sistem ke server pusat keamanan',
    optionE: 'Menghemat konsumsi daya listrik pendingin',
    correctAnswer: 'A',
    explanation: 'Safety interlock switch adalah sistem proteksi otomatis yang memutus sirkuit tegangan tinggi tabung sinar-X sehingga paparan berhenti seketika jika pintu/panel perisai dibuka.',
    isActive: true,
  },
  {
    id: 12,
    category: TrainingCategory.PPR_BAGASI,
    topic: 'Pemantauan Dosis',
    difficulty: 1,
    questionText: 'Alat pemantau dosis personal yang wajib dipakai oleh operator mesin sinar-X bagasi selama bertugas adalah...',
    optionA: 'Survey meter analog',
    optionB: 'TLD badge atau dosimeter saku digital',
    optionC: 'Pencacah Geiger-Müller genggam',
    optionD: 'Monitor kontaminasi tangan dan kaki',
    optionE: 'Termometer infra merah',
    correctAnswer: 'B',
    explanation: 'Operator wajib mengenakan dosimeter perorangan (seperti TLD badge, film badge, atau electronic personal dosimeter / EPD) yang disematkan pada pakaian kerja di bagian dada.',
    isActive: true,
  },
  {
    id: 13,
    category: TrainingCategory.PKR_PEKERJA,
    topic: 'Prinsip Dasar Proteksi',
    difficulty: 1,
    questionText: 'Tiga prinsip dasar proteksi radiasi terhadap sumber radiasi eksterna adalah...',
    optionA: 'Waktu, Jarak, dan Penahan (Perisai)',
    optionB: 'Tekanan, Suhu, dan Volume',
    optionC: 'Aktivitas, Massa, dan Kecepatan',
    optionD: 'Tegangan, Arus, dan Hambatan',
    optionE: 'Ventilasi, Pencahayaan, dan Kerapatan',
    correctAnswer: 'A',
    explanation: 'Proteksi radiasi eksterna berlandaskan 3 pilar: 1) Memperpendek waktu penyinaran, 2) Memperjauh jarak dari sumber radiasi, 3) Memasang penahan/perisai (shielding) radiasi yang memadai.',
    isActive: true,
  },
  {
    id: 14,
    category: TrainingCategory.PKR_PEKERJA,
    topic: 'Regulasi BAPETEN',
    difficulty: 2,
    questionText: 'Berdasarkan regulasi proteksi radiasi BAPETEN, Nilai Batas Dosis (NBD) ekuivalen untuk lensa mata bagi pekerja radiasi adalah...',
    optionA: '150 mSv per tahun',
    optionB: '20 mSv per tahun (rata-rata 5 tahun berturut-turut)',
    optionC: '500 mSv per tahun',
    optionD: '50 mSv dalam 10 tahun',
    optionE: '1 mSv per tahun',
    correctAnswer: 'B',
    explanation: 'Sesuai ketentuan mutakhir BAPETEN dan ICRP 103/118, NBD untuk lensa mata telah diturunkan menjadi 20 mSv/tahun rata-rata dalam 5 tahun berturut-turut tanpa melampaui 50 mSv dalam satu tahun tunggal guna mencegah katarak radiasi.',
    isActive: true,
  },
  {
    id: 15,
    category: TrainingCategory.PKR_PEKERJA,
    topic: 'Klasifikasi Daerah Kerja',
    difficulty: 1,
    questionText: 'Daerah kerja di fasilitas radiasi yang potensi penerimaan dosisnya memungkinkan pekerja menerima dosis lebih dari 3/10 NBD disebut...',
    optionA: 'Daerah Supervisi / Pengawasan',
    optionB: 'Daerah Bebas / Publik',
    optionC: 'Daerah Pengendalian (Controlled Area)',
    optionD: 'Daerah Netral',
    optionE: 'Daerah Karantina',
    correctAnswer: 'C',
    explanation: 'Daerah Pengendalian (Controlled Area) adalah area kerja di mana pekerja berpotensi menerima dosis > 3/10 NBD (6 mSv/tahun) sehingga memerlukan pengawasan ketat, pembatasan akses, dan pemantauan dosis khusus.',
    isActive: true,
  },
  {
    id: 16,
    category: TrainingCategory.PKR_PEKERJA,
    topic: 'Tanda Bahaya Radiasi',
    difficulty: 1,
    questionText: 'Simbol bahaya radiasi pengion internasional (trefoil) memiliki ciri visual berupa...',
    optionA: 'Segitiga merah dengan gambar api berkobar',
    optionB: 'Baling-baling berbilah tiga (trefoil) berwarna hitam atau magenta berlatar belakang kuning',
    optionC: 'Tengkorak putih dengan latar belakang hitam pekat',
    optionD: 'Lingkaran hijau bergaris silang putih',
    optionE: 'Bintang sudut lima berwarna oranye',
    correctAnswer: 'B',
    explanation: 'Simbol internasional bahaya radiasi adalah trefoil (propeller berbilah tiga simetris) berwarna hitam atau ungu/magenta dengan dasar bidang berwarna kuning terang.',
    isActive: true,
  },
  {
    id: 17,
    category: TrainingCategory.PKR_PEKERJA,
    topic: 'Alat Pelindung Diri (APD)',
    difficulty: 2,
    questionText: 'Bila pekerja radiasi mengenakan apron bertimbal (lead apron) saat tindakan fluoroskopi, letak pemakaian TLD badge utama yang tepat adalah...',
    optionA: 'Di kantong celana sebelah belakang',
    optionB: 'Di dada sebelah dalam apron timbal',
    optionC: 'Di luar apron pada kerah leher (collar)',
    optionD: 'Di pergelangan kaki',
    optionE: 'Diletakkan di meja operator',
    correctAnswer: 'B',
    explanation: 'Dosimeter personal utama yang mengukur dosis efektif seluruh tubuh harus dikenakan di bagian dada di balik/di dalam apron timbal (under apron). Jika memakai dosimeter kedua untuk mata/tiroid, dapat dipasang di kerah leher.',
    isActive: true,
  },
  {
    id: 18,
    category: TrainingCategory.PPR_ANALISIS,
    topic: 'Fisika Radiasi',
    difficulty: 2,
    questionText: 'Laju dosis dari suatu sumber titik radiasi gamma pada jarak 1 meter adalah 100 µSv/jam. Berdasarkan Hukum Kuadrat Terbalik, berapakah laju dosis pada jarak 2 meter dari sumber?',
    optionA: '50 µSv/jam',
    optionB: '25 µSv/jam',
    optionC: '10 µSv/jam',
    optionD: '12,5 µSv/jam',
    optionE: '200 µSv/jam',
    correctAnswer: 'B',
    explanation: 'Hukum Kuadrat Terbalik: I1 × (r1)^2 = I2 × (r2)^2. Sehingga: I2 = I1 × (r1 / r2)^2 = 100 × (1 / 2)^2 = 100 × 1/4 = 25 µSv/jam.',
    isActive: true,
  },
  {
    id: 19,
    category: TrainingCategory.PPR_ANALISIS,
    topic: 'Proteksi Radiasi',
    difficulty: 3,
    questionText: 'Suatu berkas radiasi gamma memiliki laju dosis awal 80 mGy/jam. Jika Half Value Layer (HVL) perisai timbal untuk energi tersebut adalah 1 cm, berapa ketebalan timbal yang dibutuhkan agar laju dosis turun menjadi 10 mGy/jam?',
    optionA: '1 cm',
    optionB: '2 cm',
    optionC: '3 cm',
    optionD: '4 cm',
    optionE: '8 cm',
    correctAnswer: 'C',
    explanation: 'Laju dosis tereduksi: 80 -> 40 (1 HVL) -> 20 (2 HVL) -> 10 mGy/jam (3 HVL). Karena 1 HVL = 1 cm, maka diperlukan ketebalan 3 × 1 cm = 3 cm timbal.',
    isActive: true,
  },
  {
    id: 20,
    category: TrainingCategory.PKR_PEKERJA,
    topic: 'Regulasi BAPETEN',
    difficulty: 1,
    questionText: 'Berdasarkan Peraturan Pemerintah dan Perba BAPETEN, batas dosis efektif tahunan bagi anggota masyarakat umum (non-pekerja radiasi) adalah...',
    optionA: '1 mSv per tahun',
    optionB: '5 mSv per tahun',
    optionC: '10 mSv per tahun',
    optionD: '20 mSv per tahun',
    optionE: '50 mSv per tahun',
    correctAnswer: 'A',
    explanation: 'Nilai Batas Dosis (NBD) untuk anggota masyarakat umum adalah 1 mSv per tahun (atau dapat 5 mSv dalam satu tahun tunggal asalkan rata-rata 5 tahun berturut-turut tidak melebihi 1 mSv/tahun).',
    isActive: true,
  },
];

async function main() {
  console.log('Menyimpan 20 contoh soal ke database...');
  for (const q of sampleQuestions) {
    await prisma.question.upsert({
      where: { id: q.id },
      update: {
        category: q.category,
        topic: q.topic,
        difficulty: q.difficulty,
        questionText: q.questionText,
        optionA: q.optionA,
        optionB: q.optionB,
        optionC: q.optionC,
        optionD: q.optionD,
        optionE: q.optionE,
        correctAnswer: q.correctAnswer,
        explanation: q.explanation,
        isActive: q.isActive,
      },
      create: {
        id: q.id,
        category: q.category,
        topic: q.topic,
        difficulty: q.difficulty,
        questionText: q.questionText,
        optionA: q.optionA,
        optionB: q.optionB,
        optionC: q.optionC,
        optionD: q.optionD,
        optionE: q.optionE,
        correctAnswer: q.correctAnswer,
        explanation: q.explanation,
        isActive: q.isActive,
      },
    });
  }
  const total = await prisma.question.count();
  console.log(`Berhasil! Total soal di database sekarang: ${total}`);
}

main()
  .catch((e) => {
    console.error('Error saat seeding soal:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
